# Copyright 2026 JetBrains s.r.o.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//common:provider.bzl", "intellij_provider")

_ENUM_FILE_TEMPLATE = """
// generated by //private/rules:aspect_gen.bzl - do not edit

package %s

enum class ModuleGroups(
  val pkg: String,
  val fragments: List<String>,
  val toolchains: List<String>,
) {
%s
}
"""

_ENUM_FILE_ENTRY = """
{name}(
    pkg = "{package}",
    fragments = listOf({fragments}),
    toolchains = listOf({toolchains}),
),
"""

_CONFIG_FILE_TEMPLATE = """
# generated by //private/rules:aspect_gen.bzl - do not edit

load("//intellij:aspect.bzl", "create_intellij_aspect")

intellij_aspect = create_intellij_aspect(
    modules = [{modules}],
    fragments = [{fragments}],
    toolchains = [{toolchains}],
)
"""

def _quote(value):
    return "\"%s\"" % value

def _join(values, transform):
    return ", ".join([transform(it) for it in values])

def _format_enum_group(group):
    return _ENUM_FILE_ENTRY.format(
        name = group.owner.package.removeprefix("modules/").upper(),
        package = group.owner.package,
        fragments = _join(group.fragments, _quote),
        toolchains = _join(group.toolchains, _quote),
    )

def _collect_groups(targets):
    result = []

    for target in targets:
        group = target[intellij_provider.ModuleGroup]

        fragments = set()
        toolchains = set()

        for module in group.deps:
            fragments.update(module.fragments)
            toolchains.update(module.toolchains)

        result.append(struct(
            owner = group.owner,
            fragments = list(fragments),
            toolchains = list(toolchains),
        ))

    return result

def _aspect_gen_enum_impl(ctx):
    groups = [_format_enum_group(it) for it in _collect_groups(ctx.attr.modules)]

    file = ctx.actions.declare_file(ctx.attr.out)
    ctx.actions.write(file, _ENUM_FILE_TEMPLATE % (ctx.attr.package, "\n".join(groups)))

    return [DefaultInfo(files = depset([file]))]

aspect_gen_enum = rule(
    implementation = _aspect_gen_enum_impl,
    attrs = {
        "out": attr.string(
            doc = "The output file name, should have the .kt extension.",
            mandatory = True,
        ),
        "package": attr.string(
            doc = "The packate of the generated ModuleGroups enum.",
            mandatory = True,
        ),
        "modules": attr.label_list(
            providers = [intellij_provider.ModuleGroup],
            mandatory = True,
        ),
    },
)

def _format_label(label):
    return "\"//%s:%s\"" % (label.package, label.name)

def _aspect_gen_config_impl(ctx):
    modules = set()
    fragments = set()
    toolchains = set()

    for group in _collect_groups(ctx.attr.modules):
        modules.add(group.owner)
        fragments.update(group.fragments)
        toolchains.update(group.toolchains)

    config = _CONFIG_FILE_TEMPLATE.format(
        modules = _join(modules, _format_label),
        fragments = _join(fragments, _quote),
        toolchains = _join(toolchains, _quote),
    )

    file = ctx.actions.declare_file(ctx.attr.out)
    ctx.actions.write(file, config)

    return [DefaultInfo(files = depset([file]))]

aspect_gen_config = rule(
    implementation = _aspect_gen_config_impl,
    attrs = {
        "out": attr.string(
            doc = "The output file name, should have the .bzl extension.",
            mandatory = True,
        ),
        "modules": attr.label_list(
            providers = [intellij_provider.ModuleGroup],
            mandatory = True,
        ),
    },
)
