header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: JetBrains s.r.o. and contributors
    pattern: Copyright \d{4}
  paths:
    - '**/*.kt'
    - '**/*.java'
    - '**/*.bzl'
    - '**/*.proto'
  paths-ignore:
    - 'testing/fixtures/**'
    - 'private/repos/common.bzl'
  comment: on-failure
