load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    fixture = "//testing/fixtures/cpp:builtin",
    test = "BuiltinRulesTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:tool",
    test = "ToolDepTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:simple",
    test = "InfoTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:simple",
    test = "ToolchainTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:simple",
    test = "TestInfoTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:abseil",
    test = "AbseilTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/cpp:layout",
    test = "LayoutTest.kt",
)
