load("//modules:module.bzl", "intellij_module")
load(":empty_0.bzl", "empty_0")
load(":empty_1.bzl", "empty_1")
load(":empty_2.bzl", "empty_2")
load(":empty_3.bzl", "empty_3")
load(":empty_4.bzl", "empty_4")
load(":empty_5.bzl", "empty_5")
load(":empty_6.bzl", "empty_6")
load(":empty_7.bzl", "empty_7")

intellij_module.declare(
    name = "empty_0",
    rule = empty_0,
)

intellij_module.declare(
    name = "empty_1",
    rule = empty_1,
)

intellij_module.declare(
    name = "empty_2",
    rule = empty_2,
)

intellij_module.declare(
    name = "empty_3",
    rule = empty_3,
)

intellij_module.declare(
    name = "empty_4",
    rule = empty_4,
)

intellij_module.declare(
    name = "empty_5",
    rule = empty_5,
)

intellij_module.declare(
    name = "empty_6",
    rule = empty_6,
)

intellij_module.declare(
    name = "empty_7",
    rule = empty_7,
)

intellij_module.filegroup()
