load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    fixture = "//testing/fixtures/java:simple",
    test = "SimpleTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/java:macro",
    test = "MacroTest.kt",
)
