load("//testing/rules:defs.bzl", "junit_test")

junit_test(
    test = "ReadTargetTest.kt",
    deps = [
        "//sdk",
        "//sdk/proto:ide_info_java_proto",
        "@protobuf//:protobuf_java",
    ],
)
