load("//testing/rules:defs.bzl", "test_runner")

test_runner(
    fixture = "//testing/fixtures/scala:simple",
    test = "SimpleTest.kt",
)

test_runner(
    fixture = "//testing/fixtures/scala:generated",
    test = "GeneratedSourcesTest.kt",
)
