/*
 * Copyright 2026 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.intellij.aspect.lib

import com.intellij.aspect.private.lib.utils.asBazelPath
import java.io.IOException
import java.nio.file.Files
import java.nio.file.Path
import java.util.Locale

/**
 * Creates the config directory and writes the config file and the aspect configuration, as well as
 * the required BUILD file.
 */
@Throws(IOException::class)
fun writeAspectConfig(destination: Path, relativeDestination: Path, config: AspectConfig) {
  val directory = destination.resolve("config")
  Files.createDirectories(directory)

  val buildFile = directory.resolve("BUILD")
  writeFileIfContentDiffers(buildFile, "# generated by //sdk/lib/config.kt - do not edit\n")

  val configFile = directory.resolve("config.bzl")
  writeFileIfContentDiffers(configFile, generateConfigStruct(config))

  val aspectFile = directory.resolve("aspect.bzl")
  writeFileIfContentDiffers(aspectFile, generateAspectConfig(relativeDestination, config))
}

private fun generateConfigStruct(config: AspectConfig) = """
# generated by //sdk/lib/config.kt - do not edit

config = struct(
	bazel_version = "${config.bazelVersion}",
  os = "${System.getProperty("os.name").lowercase(Locale.ROOT)}",
)
"""

private fun quote(s: String) = "\"$s\""

private fun generateAspectConfig(relativeDestination: Path, config: AspectConfig): String {
  val groups = moduleGroupsForRules(config.rules)
  val prefix = asBazelPath(relativeDestination)

  val modules = groups.map { "//$prefix/${it.pkg}" }.sorted()
  val fragments = groups.flatMap(ModuleGroups::fragments).distinct().sorted()
  val toolchains = groups.flatMap(ModuleGroups::toolchains).distinct().sorted()

  return """
# generated by //sdk/lib/config.kt - do not edit

load("//$prefix/intellij:aspect.bzl", "create_intellij_aspect")

intellij_aspect = create_intellij_aspect(
    modules = [${modules.joinToString(", ", transform = ::quote)}],
    fragments = [${fragments.joinToString(", ", transform = ::quote)}],
    toolchains = [${toolchains.joinToString(", ", transform = ::quote)}],
)
"""
}
