load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "sdk",
    visibility = ["//visibility:public"],
    exports = [
        "//sdk/lib:deploy",
        "//sdk/proto:common_java_proto",
        "//sdk/proto:ide_info_java_proto",
    ],
)
