name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest-8-core-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.18.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true

    - name: Build all targets
      run: bazel build //... --lockfile_mode=error

    - name: Test all targets
      run: bazel test //... --test_output=errors

  license-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check License Header
      uses: apache/skywalking-eyes/header@v0.8.0
      with:
        mode: check
